### ISSUE TITLE
Undeclared Indentifier (alphas) at dwm-alpha-6.2.diff

### ISSUE THREAD

**Issue by ltsdw** [bakkeby/patches#1]
Sadly I'm not skilled enough to handle it myself.

```
dwm.c: In function ‘setup’:
dwm.c:1600:46: error: ‘alphas’ undeclared (first use in this function)
 1600 |   scheme[i] = drw_scm_create(drw, colors[i], alphas[i], 3);
      |                                              ^~~~~~
dwm.c:1600:46: note: each undeclared identifier is reported only once for each function it appears in
At top level:
```

**Comment by bakkeby** [comment]
This just says that `alphas` is not defined. If you have a look at the different then you can see that it's a variable that is defined in the default config.def.h.
Your issue would be that you didn't delete your personal config.h file before compiling, or copying in the changes manually if you have made changes to config.h.

**Comment by ltsdw** [comment]
Oh my... I just read this on some forums and even though didn't set right my config.h, everything is working now :)
