### ISSUE TITLE
Fullscreen compilation - conflict with noborders patch and fakefullscreen

### ISSUE THREAD

**Issue by paniash** [bakkeby/patches#10]
Hello there,

I just patched my dwm build with fullscreen compilation and also use the [noborder patch](https://dwm.suckless.org/patches/noborder/dwm-noborder-6.2.diff). 

When a window is in a tiled mode (fakescreen toggle off) and when I switch to monocle mode, the borders vanish as expected. However the main issue is when fakefullscreen is toggled on when in tiling mode and then I switch over to monocle mode. The borders in this case remain visible. But if I enter monocle mode with fakefullscreen toggle off and then I turn it on, the borders vanish. Is this a known bug that is addressed in #9?. I got lost with the technicality and hence am asking this issue. Pardon me if it's already addressed.

Thanks in advance!

**Comment by bakkeby** [comment]
I think this is merely a conflict between the patches. I'm planning on adding a standalone noborder patch that goes on top of the fullscreen compilation, but I have been focusing on polishing the main patch ref. the issues in #9 that vide0hanz has found through his regression testing.

The [noborder](https://dwm.suckless.org/patches/noborder/dwm-noborder-6.2.diff) adds this to the `resizeclient` function:
```c
+	if (((nexttiled(c->mon->clients) == c && !nexttiled(c->next))
+	    || &monocle == c->mon->lt[c->mon->sellt]->arrange)
+	    && !c->isfullscreen && !c->isfloating) {
+		c->w = wc.width += c->bw * 2;
+		c->h = wc.height += c->bw * 2;
+		wc.border_width = 0;
+	}
```

You should replace the `&& !c->isfullscreen` with `&& (c->fakefullscreen == 1 || !c->isfullscreen)` and I think the issue with the monocle layout should go away.

I'll push a complementary patch for this.

**Comment by paniash** [comment]
@bakkeby Thanks a lot! It worked :+1:

**Comment by bakkeby** [comment]
Added that now, also note the addition of `&& c->mon->lt[c->mon->sellt]->arrange` as you probably do not want the border to go away in floating layout.

**Comment by bakkeby** [comment]
Updated https://github.com/bakkeby/patches/wiki/fullscreen-compilation with a link to the new patch, I'll mark this as closed now.

**Comment by paniash** [comment]
> Added that now, also note the addition of `&& c->mon->lt[c->mon->sellt]->arrange` as you probably do not want the border to go away in floating layout.

The borders do appear in floating windows without this line. Maybe I'm missing something?

**Comment by bakkeby** [comment]
If you look at the noborder patch (diff) then it explicitly does not remove the border if the client window is floating (`&& !c->isfloating`), which means that all floating windows have a border right.

But, if you change to _floating layout_ then all clients that were previously tiled will have no border. This was actually addressed in [https://dwm.suckless.org/patches/noborder/dwm-noborderfloatingfix-6.2.diff](https://dwm.suckless.org/patches/noborder/dwm-noborderfloatingfix-6.2.diff). If I remember correctly if you move such a floating tiled window without a border around with the mouse then it will continuously grow

**Comment by paniash** [comment]
Yes, you are right. I did face the issue of floating windows continuously growing and that line seemed to have fixed it. Thanks a lot!
