### ISSUE TITLE
monitorrules patch error.

### ISSUE THREAD

**Issue by apoorv569** [bakkeby/patches#13]
I patched my `dwm` with `pertag` patch and then I tried to apply your `monitorrules` patch, I am getting a error when `make`, `monrules` undeclared, I don't know what is causing it, there is `monrules` patched successfully to `config.def.h` and also it gives error about `pertag` has no member `prevzooms`.

Full error
```
dwm.c:849:28: error: ‘monrules’ undeclared (first use in this function); did you mean ‘rules’?
  849 |     for (j = 0; j < LENGTH(monrules); j++) {
      |                            ^~~~~~~~
dwm.c:54:41: note: in definition of macro ‘LENGTH’
   54 | #define LENGTH(X)               (sizeof X / sizeof X[0])
      |                                         ^
dwm.c:849:28: note: each undeclared identifier is reported only once for each function it appears in
  849 |     for (j = 0; j < LENGTH(monrules); j++) {
      |                            ^~~~~~~~
dwm.c:54:41: note: in definition of macro ‘LENGTH’
   54 | #define LENGTH(X)               (sizeof X / sizeof X[0])
      |                                         ^
dwm.c:881:18: error: ‘Pertag’ has no member named ‘prevzooms’
  881 |         m->pertag->prevzooms[i] = NULL;
      |                  ^~
make: *** [Makefile:18: dwm.o] Error 1
```

My `dwm.c`

```
Monitor *
createmon(void)
{
    Monitor *m, *mon;
    int i, mi, j, layout;
    const MonitorRule *mr;

	m = ecalloc(1, sizeof(Monitor));
	m->tagset[0] = m->tagset[1] = 1;
	m->mfact = mfact;
	m->nmaster = nmaster;
	m->showbar = showbar;
	m->topbar = topbar;
	m->gappih = gappih;
	m->gappiv = gappiv;
	m->gappoh = gappoh;
	m->gappov = gappov;

    for (mi = 0, mon = mons; mon; mon = mon->next, mi++);
    for (j = 0; j < LENGTH(monrules); j++) {
        mr = &monrules[j];
        if ((mr->monitor == -1 || mr->monitor == mi)
                && (mr->tag <= 0 || (m->tagset[0] & (1 << (mr->tag - 1))))
        ) {
            layout = MAX(mr->layout, 0);
            layout = MIN(layout, LENGTH(layouts) - 1);
            m->lt[0] = &layouts[layout];
            m->lt[1] = &layouts[1 % LENGTH(layouts)];
            strncpy(m->ltsymbol, layouts[layout].symbol, sizeof m->ltsymbol);
 
            if (mr->mfact > -1)
               m->mfact = mr->mfact;
            if (mr->nmaster > -1)
                m->nmaster = mr->nmaster;
            if (mr->showbar > -1)
               m->showbar = mr->showbar;
            if (mr->topbar > -1)
               m->topbar = mr->topbar;
            break;
        }
    }

    if (!(m->pertag = (Pertag *)calloc(1, sizeof(Pertag))))
        die("fatal: could not malloc() %u bytes\n", sizeof(Pertag));
    m->pertag->curtag = m->pertag->prevtag = 1;

    for (i = 0; i <= LENGTH(tags); i++) {
        /* init layouts */
        m->pertag->sellts[i] = m->sellt;
  
        /* swap focus and zoomswap*/
        m->pertag->prevzooms[i] = NULL;
  
        for (j = 0; j < LENGTH(monrules); j++) {
            mr = &monrules[j];
            if ((mr->monitor == -1 || mr->monitor == mi) && (mr->tag == -1 || mr->tag == i)) {
                layout = MAX(mr->layout, 0);
                layout = MIN(layout, LENGTH(layouts) - 1);
                m->pertag->ltidxs[i][0] = &layouts[layout];
                m->pertag->ltidxs[i][1] = m->lt[0];
                m->pertag->nmasters[i] = (mr->nmaster > -1 ? mr->nmaster : m->nmaster);
                m->pertag->mfacts[i] = (mr->mfact > -1 ? mr->mfact : m->mfact);
                m->pertag->showbars[i] = (mr->showbar > -1 ? mr->showbar : m->showbar);
                break;
            }
        }
    }

	return m;
}
```

**Comment by bakkeby** [comment]
The [dwm-pertag-monitorrules-6.2.diff](https://github.com/bakkeby/patches/blob/master/dwm/dwm-pertag-monitorrules-6.2.diff) patch depends on [dwm-pertag-6.2.diff](https://github.com/bakkeby/patches/blob/master/dwm/dwm-pertag-6.2.diff) having been applied, I presume you are using another pertag patch. If you don't use / need the prevzooms then just delete that line.

About monrules not existing. As you say the patch added monrules to the config.def.h. When you compile config.def.h is copied to config.h if it does not already exist. Presumably you already have a config.h that does not have monrules.

Assuming you have made changes to your config.h just copy in the relevant bits from config.def.h manually.

**Comment by apoorv569** [comment]
> The [dwm-pertag-monitorrules-6.2.diff](https://github.com/bakkeby/patches/blob/master/dwm/dwm-pertag-monitorrules-6.2.diff) patch depends on [dwm-pertag-6.2.diff](https://github.com/bakkeby/patches/blob/master/dwm/dwm-pertag-6.2.diff) having been applied, I presume you are using another pertag patch. If you don't use / need the prevzooms then just delete that line.
> 
> About monrules not existing. As you say the patch added monrules to the config.def.h. When you compile config.def.h is copied to config.h if it does not already exist. Presumably you already have a config.h that does not have monrules.
> 
> Assuming you have made changes to your config.h just copy in the relevant bits from config.def.h manually.

I have `dwm-pertag-20200914-61bb8b2.diff` patched before I patched `monitorrules`, `pertag` patch works in it self, but monitor patch won't get patch correctly. I did remove my old `config.h` before running `make` again, no luck. I guess the problem is with the `pertag` version I downloaded. Also what is `prevzooms`?

**Comment by bakkeby** [comment]
In dwm the `zoom` function rotates the entire stack so that the focused client becomes the new master.

The [zoomswap](https://dwm.suckless.org/patches/zoomswap/) patch changes the `zoom` functionality such that the stack doesn't rotate, instead the currently focused client and the current master swap places. It remembers the previously zoomed master in a variable `prevzoom` so that you can swap back and forth between them.

The `prevzooms` array in pertag just extends that functionality to remember the previous zoom on a per tag basis.

I should probably just replace it with an integration hint.

**Comment by apoorv569** [comment]
> In dwm the `zoom` function rotates the entire stack so that the focused client becomes the new master.
> 
> The [zoomswap](https://dwm.suckless.org/patches/zoomswap/) patch changes the `zoom` functionality such that the stack doesn't rotate, instead the currently focused client and the current master swap places. It remembers the previously zoomed master in a variable `prevzoom` so that you can swap back and forth between them.
> 
> The `prevzooms` array in pertag just extends that functionality to remember the previous zoom on a per tag basis.
> 
> I should probably just replace it with an integration hint.

I don't have this `zoomswap` patch aplied maybe that's why it failed.

BTW, I hope you remember me, I was the guy who was having problem with `systray` and `status2d` patch. About a month ago, I started learning `C++`, a lot of things now, looking at the source code, makes sense to me now. I am not yet ready for such modifications, but some things makes sense now at least.

**Comment by bakkeby** [comment]
I do remember you :)

Just patching zoomswap doesn't make any difference as the zoomswap patch is not aware of the pertag patch. There are some integration hints in my dwm-flexipatch build, but as I said before you can just delete the two lines that don't apply.

You'll also save yourself a lot of hassle if you just merge patches manually by hand rather than solely relying on `patch` and/or `git apply`.

**Comment by apoorv569** [comment]
> I do remember you :)
> 
> Just patching zoomswap doesn't make any difference as the zoomswap patch is not aware of the pertag patch. There are some integration hints in my dwm-flexipatch build, but as I said before you can just delete the two lines that don't apply.
> 
> You'll also save yourself a lot of hassle if you just merge patches manually by hand rather than solely relying on `patch` and/or `git apply`.

I see, I commented those lines, it compiles fine now. :D
