### ISSUE TITLE
cfacts-vanitygaps patch

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/patches#14]
I think the cfacts-vanitygaps patch is broken .. it doesn't implement the cfacts function at all, or is this supposed to be applied on top of cfacts?

**Comment by bakkeby** [comment]
Yes it's meant to be added on top of cfacts.

**Comment by kronikpillow** [comment]
doesn't seem to be the case, I get compilation errors once I apply cfacts-vanitygaps on top of vanitygaps .... I'm doing this on a clean dwm build, I applied patches in this order: vanitygaps, cfacts, cfacts-vanitygaps, not entirely sure how this is supposed to actually work .. the vanitygaps patch removes tile layout from dwm.c and places it in to vanitygaps.c but the cfacts-vanitygaps does the same thing, or attemtps to do the same thing, althou doesn't input all the cfacts related functions ... also the decklayout uses the wrong layout indicator symbol in the patch

**Comment by bakkeby** [comment]
It's meant to be added on top of cfacts.
