### ISSUE TITLE
Togglegaps with pertag patch

### ISSUE THREAD

**Issue by paniash** [bakkeby/patches#15]
Hi!

I'm using the `togglegaps()` function from `vanitygaps.c` but this works for all tags. Is there a way to only toggle gaps for the currently active tag, just like how the pertag patch works.

I've tried removing the relevant lines from the function but I get a compilation error.

```c
void
togglegaps(const Arg *arg)
{
	#if PERTAG_PATCH  // <-- removed this
	selmon->pertag->enablegaps[selmon->pertag->curtag] = !selmon->pertag->enablegaps[selmon->pertag->curtag];
	#else  // <-- removed this
	enablegaps = !enablegaps;  // <-- removed this
	#endif // PERTAG_PATCH  // <-- removed this
	arrange(NULL);
}
```

Thanks!

**Comment by bakkeby** [comment]
Yes that's only a partial integration hint.

You'll want to add this in the Pertag struct:
https://github.com/bakkeby/dwm-flexipatch/blob/b837899f7aff816895ae892f965be461c8b027ef/patch/pertag.c#L23

and this in the `createmon` function:
https://github.com/bakkeby/dwm-flexipatch/blob/b837899f7aff816895ae892f965be461c8b027ef/dwm.c#L1372

**Comment by paniash** [comment]
@bakkeby Hi! I added the lines as you suggested but unfortunately, there is no difference. :(

**Comment by bakkeby** [comment]
Do you still get compilation errors?

I guess the code to set enablegaps in `toggleview` and `view` are missing.

**Comment by bakkeby** [comment]
Should be something like
```c
selmon->enablegaps = selmon->pertag->enablegaps[selmon->pertag->curtag];
```

**Comment by paniash** [comment]
> Should be something like
> 
> ```c
> selmon->enablegaps = selmon->pertag->enablegaps[selmon->pertag->curtag];
> ```

After this, I get the following compilation error:
```c
dwm.c: In function ‘toggleview’:
dwm.c:2339:9: error: ‘Monitor’ has no member named ‘enablegaps’
 2339 |   selmon->enablegaps = selmon->pertag->enablegaps[selmon->pertag->curtag]; // compatibility with pertag and togglegaps
      |         ^~
dwm.c: In function ‘view’:
dwm.c:2812:8: error: ‘Monitor’ has no member named ‘enablegaps’
 2812 |  selmon->enablegaps = selmon->pertag->enablegaps[selmon->pertag->curtag]; // compatibility with pertag and togglegaps
      |        ^~
make: *** [Makefile:18: dwm.o] Error 1
```

**Comment by bakkeby** [comment]
Ah I guess it wasn't that then, sorry in on mobile. 

Do you have this?

https://github.com/bakkeby/dwm-flexipatch/blob/b837899f7aff816895ae892f965be461c8b027ef/patch/vanitygaps.c#L117-L122

**Comment by paniash** [comment]
> Do you have this?
> 
> https://github.com/bakkeby/dwm-flexipatch/blob/b837899f7aff816895ae892f965be461c8b027ef/patch/vanitygaps.c#L117-L122

Yup.

**Comment by bakkeby** [comment]
Then you know what to do :D

**Comment by paniash** [comment]
> Then you know what to do :D

Unfortunately, compilation error. :(
```
In file included from config.h:83,
                 from dwm.c:343:
vanitygaps.c: In function ‘getgaps’:
vanitygaps.c:147:26: error: invalid use of incomplete typedef ‘Pertag’
  147 |  oe = ie = selmon->pertag->enablegaps[selmon->pertag->curtag];
      |                          ^~
vanitygaps.c:147:53: error: invalid use of incomplete typedef ‘Pertag’
  147 |  oe = ie = selmon->pertag->enablegaps[selmon->pertag->curtag];
      |                                                     ^~
dwm.c: In function ‘toggleview’:
dwm.c:2339:9: error: ‘Monitor’ has no member named ‘enablegaps’
 2339 |   selmon->enablegaps = selmon->pertag->enablegaps[selmon->pertag->curtag]; // compatibility with pertag
and togglegaps
      |         ^~
dwm.c: In function ‘view’:
dwm.c:2812:8: error: ‘Monitor’ has no member named ‘enablegaps’
 2812 |  selmon->enablegaps = selmon->pertag->enablegaps[selmon->pertag->curtag]; // compatibility with pertag and togglegaps
      |        ^~
make: *** [Makefile:18: dwm.o] Error 1
```

**Comment by bakkeby** [comment]
You should be able to work out what these errors mean and why they happen.

You can delete the two 2339 and 2812 lines in dwm.c.

You need to ensure that you have that `int enablegaps[LENGTH(tags) + 1]; /* added with vanitygaps */` line in `Pertag` as per your earlier comment.

And also the `m->pertag->enablegaps[i] = 1;  // compatibility with pertag and togglegaps` line in `createmon`.

**Comment by paniash** [comment]
Thanks! It compiles fine but works just like it used to (togglegaps for all tags simultaneously).

**Comment by bakkeby** [comment]
Then you haven't removed all the corresponding PERTAG_PATCH references. Alternatively you can also set `#define PERTAG_PATCH 1` before vanitygaps.c is sourced to enable it.

**Comment by paniash** [comment]
I went with the latter approach and added it to `config.h` as follows:
```c
#define FORCE_VSPLIT 1  /* nrowgrid layout: force two clients to always split vertically */
#include "vanitygaps.c"
#define PERTAG_PATCH 1
```

However, adding `#define PERTAG_PATCH 1` **before** `#include "vanitygaps.c"` yields compilation error.

**Comment by bakkeby** [comment]
Including it after has no effect, so that is a given. 

You either need to deal with the complication errors or consider going back to before you started making changes and only add the changes you need.

**Comment by paniash** [comment]
Apologies for the trouble but I've only added the following as per your suggestion:
 
> You need to ensure that you have that `int enablegaps[LENGTH(tags) + 1]; /* added with vanitygaps */` line in `Pertag` as per your earlier comment.
> 
> And also the `m->pertag->enablegaps[i] = 1; // compatibility with pertag and togglegaps` line in `createmon`.


> ```c
> #define FORCE_VSPLIT 1  /* nrowgrid layout: force two clients to always split vertically */
> #include "vanitygaps.c"
> #define PERTAG_PATCH 1
> ```

Is there anything else that I'm missing? I can't seem to figure it out. :(

**Comment by bakkeby** [comment]
Ah ok, I see now. It is actually fine.

What is happening in dwm.c is this:
```c
/* configuration, allows nested code to access above variables */
#include "config.h"

struct Pertag {
    unsigned int curtag, prevtag; /* current and previous tag */
    int nmasters[LENGTH(tags) + 1]; /* number of windows in master area */
    float mfacts[LENGTH(tags) + 1]; /* mfacts per tag */
    unsigned int sellts[LENGTH(tags) + 1]; /* selected layouts */
    const Layout *ltidxs[LENGTH(tags) + 1][2]; /* matrix of tags and layouts indexes  */
    int showbars[LENGTH(tags) + 1]; /* display bar for the current tag */
    int enablegaps[LENGTH(tags) + 1]; /* added with vanitygaps */
};
```
The config.h in turn sources vanitygaps.c and we hit a bit of a chicken and egg situation with regards to dependencies.

vanitygaps depends on `pertag->enablegaps`
pertag depends on the `tags` variable defined in config.h
config.h depends on functions (layouts) defined in vanitygaps

What I would recommend that you do is to split the vanitygaps.c file into two, so that you have vanitygaps.h containing the top part of what is currently in vanitygaps.c:
```c
/* Key binding functions */
static void defaultgaps(const Arg *arg);
static void incrgaps(const Arg *arg);
static void incrigaps(const Arg *arg);
static void incrogaps(const Arg *arg);
static void incrohgaps(const Arg *arg);
static void incrovgaps(const Arg *arg);
static void incrihgaps(const Arg *arg);
static void incrivgaps(const Arg *arg);
static void togglegaps(const Arg *arg);
/* Layouts (delete the ones you do not need) */
/* static void bstack(Monitor *m); */
/* static void bstackhoriz(Monitor *m); */
/* static void centeredmaster(Monitor *m); */
/* static void centeredfloatingmaster(Monitor *m); */
/* static void deck(Monitor *m); */
/* static void dwindle(Monitor *m); */
/* static void fibonacci(Monitor *m, int s); */
/* static void grid(Monitor *m); */
/* static void nrowgrid(Monitor *m); */
/* static void spiral(Monitor *m); */
static void tile(Monitor *m);
/* Internals */
static void getgaps(Monitor *m, int *oh, int *ov, int *ih, int *iv, unsigned int *nc);
static void getfacts(Monitor *m, int msize, int ssize, float *mf, float *sf, int *mr, int *sr);
static void setgaps(int oh, int ov, int ih, int iv);
```

That vanitygaps.h file you can source in place of vanitygaps.c in config.h, or just do it separately in dwm.c so that you have:
```c
#include "vanitygaps.h"

/* configuration, allows nested code to access above variables */
#include "config.h"

struct Pertag {
    unsigned int curtag, prevtag; /* current and previous tag */
    int nmasters[LENGTH(tags) + 1]; /* number of windows in master area */
    float mfacts[LENGTH(tags) + 1]; /* mfacts per tag */
    unsigned int sellts[LENGTH(tags) + 1]; /* selected layouts */
    const Layout *ltidxs[LENGTH(tags) + 1][2]; /* matrix of tags and layouts indexes  */
    int showbars[LENGTH(tags) + 1]; /* display bar for the current tag */
    int enablegaps[LENGTH(tags) + 1]; /* added with vanitygaps */
};

#include "vanitygaps.c"
```
Alternatively if you don't want the separate files then you can include all the code in dwm.c.

**Comment by paniash** [comment]
@bakkeby Thanks a lot! I went with the latter approach and included the `#include` calls in `dwm.c`. One minor issue though (unrelated to the thread), I'm trying to add an indicator to the tags with no gaps enabled and added the following line in `config.h`:

```c
static const Layout layouts[] = {
	/* symbol     arrange function */
	{ "[]=",      tile },    /* first entry is default */
	{ "><>",      NULL },    /* no layout function means floating behavior */
	{ "[M]",      monocle },
	{ "[G]",      togglegaps },
};
```

However, this doesn't work. Could you help me with this?

**Comment by paniash** [comment]
No worries. There was an easy fix all this while!

I simply added the `void tile(Monitor *m)` from vanilla dwm (since it doesn't have gaps by default) to `dwm.c` and added it as a layout. 

Thanks a lot @bakkeby and apologies for all the trouble.

**Comment by bakkeby** [comment]
Sure, but if you are wondering how it works then adding togglegaps to the layouts array doesn't work because it is expecting an arrange function that has a certain signature. 

Search the code for `sprintf`, there should be an example in the monocle layout function where the layout symbol is updated with the count of clients. 

In the tile function you could check if gaps are enabled and print your indicator, and otherwise print the default "[]=" symbols.

**Comment by paniash** [comment]
@bakkeby Your approach seems better! I'm not sure though which variable helps check if gaps are enabled or not. :(

**Comment by bakkeby** [comment]
Right, the name was `snprintf`.

The variable is `enablegaps` which has been moved to Pertag.

Try adding this in the tile function for vanitygaps.c:
```c
    if (selmon->pertag->enablegaps[selmon->pertag->curtag])
        snprintf(m->ltsymbol, sizeof m->ltsymbol, "[G]");
    else
        snprintf(m->ltsymbol, sizeof m->ltsymbol, "[]=");
```
(after the first return if n == 0)
