### ISSUE TITLE
Ideas on how to improve the placemouse patch

### ISSUE THREAD

**Issue by jzbor** [bakkeby/patches#20]
So after I implemented your patch I had the idea to have the mouse left button execute placemouse if tiled and movemouse if floating. It feels more natural to me and you can still float a window with the mouse via the middle button. The (simple) code is as follows:
```C
void
moveorplace(const Arg *arg) {
    if (ISFLOATING)
        movemouse(arg);
    else
        placemouse(arg);
}
```
with
```C
#define ISFLOATING              (!selmon->lt[selmon->sellt]->arrange || selmon->sel->isfloating)
```

Also I think I found a bug: When dropping the window into the master area for example and then move the mouse to focus another window it receives focus, but the borders don't take the focused color. You can easily mitigate this by always calling `focus(c)` instead of only calling it if the monitor has changed. Like this:
```C
		arrangemon(c->mon);
		c->mon = m;
		attach(c);
		attachstack(c);
		selmon = m;
	}

        focus(c);
	c->beingmoved = 0;
```

**Comment by bakkeby** [comment]
Ah this one, I remember seeing the email but wondered where this went.

I agree on both points. The `moveorplace` function is quite comfortable to use, maybe intuitive even, and the focus issue is a bug - I'll fix that.

I am not going to add the `moveorplace` function in the main patch, but I'll add it as a recommendation on the wiki page instead.

**Comment by bakkeby** [comment]
Actually I changed my mind and incorporated the `moveorplace` function into the main patch after all. Thanks.

**Comment by bakkeby** [comment]
https://github.com/bakkeby/patches/wiki/placemouse updated
