### ISSUE TITLE
Adding toggle systray?

### ISSUE THREAD

**Issue by romariorobby** [bakkeby/patches#24]
hi if you dont mind,i want to be able to toggle systray . this what i've done so far.
```C
void
togglesystray()
{
	if (showsystray)
		XUnmapWindow(dpy, systray->win);
	showsystray = !showsystray;
	drawbarwin(systray->bar);
} 
```

**Comment by bakkeby** [comment]
Does that work at all? I wouldn't have thought that you could simply unmap the window and be done with it.

Most likely you will end up having to move the systray window (and possibly the individual icons, not sure) out of the visible area like dwm does for clients in the `showhide` function.

Then you'd have to have the bar reclaim the space that the systray occupied, a solution which would depend on the implementation of systray that you have.

**Comment by romariorobby** [comment]
I'm using bar modules patch btw

**Comment by romariorobby** [comment]
it does work but when i toggle back the systray doesn't show up.

**Comment by romariorobby** [comment]
i'm using bar module patch btw

**Comment by bakkeby** [comment]
> it does work but when i toggle back the systray doesn't show up.

Likely because there is nothing mapping the window back again. I am also wondering if the systray icons end up getting unmapped as well.

Could you try this instead and see if it works for you?

```c
void
togglesystray()
{
	showsystray = !showsystray;
	drawbarwin(systray->bar);
} 
```

```diff
diff --git a/patch/bar_systray.c b/patch/bar_systray.c
index b1efe88..74ea9cd 100644
--- a/patch/bar_systray.c
+++ b/patch/bar_systray.c
@@ -17,6 +17,8 @@ int
 draw_systray(Bar *bar, BarDrawArg *a)
 {
        if (!showsystray)
+               if (systray)
+                       XMoveWindow(dpy, systray->win, -500, bar->by);
                return a->x;

        XSetWindowAttributes wa;
```

I tried this in another build of mine and it seems to do the trick.

**Comment by romariorobby** [comment]
hmmm it doesn't seems to work for me. its crashed when i hit togglesystray key.

**Comment by bakkeby** [comment]
Hmm, did you keep the unmapping in the `togglesystray` function?

The diff should have included braces of course.

```diff
diff --git a/patch/bar_systray.c b/patch/bar_systray.c
index b1efe88..3ae2e56 100644
--- a/patch/bar_systray.c
+++ b/patch/bar_systray.c
@@ -16,8 +16,11 @@ width_systray(Bar *bar, BarWidthArg *a)
 int
 draw_systray(Bar *bar, BarDrawArg *a)
 {
-       if (!showsystray)
+       if (!showsystray) {
+               if (systray)
+                       XMoveWindow(dpy, systray->win, -500, bar->by);
                return a->x;
+       }

        XSetWindowAttributes wa;
        Client *i;
```

**Comment by romariorobby** [comment]
Yes of course..

**Comment by romariorobby** [comment]
ahhh theres something silly mistake i've done... it works now. thanks for the help :+1:
