### ISSUE TITLE
dwm-pertag-monitorrules

### ISSUE THREAD

**Issue by vide0hanz** [bakkeby/patches#3]
Very minor discrepancy in the pertag-monitorrules patch you have in config.def.h - the comments for the default and secondary displays appear to be swapped.

The top line suggests suggests a secondary display, when in my case setting these rules applies to the primary. I haven't ruled out the fact that I am setting my primary display via the Nvidia driver on my end, however. 

Again, nothing major, but for the sake of consistency I just wanted to point that out.

**Comment by bakkeby** [comment]
The above refers to the following comments:
```
+static const MonitorRule monrules[] = {
+   /* monitor layout  mfact  nmaster  showbar  topbar */
+   {  1,      2,      -1,    -1,      -1,      -1     }, // use a different layout for the second monitor
+   {  -1,     0,      -1,    -1,      -1,      -1     }, // default
+};
```
> use a different layout for the second monitor

Yes you are right. In my experience the primary monitor (if specified) typically ends up as monitor 0, then subsequent monitors get 1 and 2 respectively. Unrelated, but this can also cause a mismatch for the `j` and `k` keybindings (going left when you want to go right, and vice versa).

I haven't checked, but if you don't specify the primary monitor then presumably the monitor index depends solely on what comes through `xrandr`.

You can potentially tweak the order of the monitors by changing the order passed in to `xrandr`. Another way to more or less guarantee the order of the monitors is to use the [sortscreens](https://www.mail-archive.com/hackers@suckless.org/msg09400.html) patch which reorders the monitors based on the x-axis. This way monitor 0 will always be the leftmost monitor.

Do you think that it would be better to word it like this?
> use a different layout for the monitor with index 1

As for the default this isn't actually referring to the primary monitor, but rather default settings if no other monitor rule is matched. In practice this is redundant as it just falls back to using whatever global mfact, nmaster, etc. settings are used.

**Comment by vide0hanz** [comment]
Somehow missed your reply, 

> As for the default this isn't actually referring to the primary monitor, but rather default settings if no other monitor rule is matched. In practice this is redundant as it just falls back to using whatever global mfact, nmaster, etc. settings are used.

Actually this makes sense, I was interpreting "default" as "default monitor"

**Comment by bakkeby** [comment]
Going to consider this as closed.
