### ISSUE TITLE
Multiple memory leaks

### ISSUE THREAD

**Issue by jzbor** [bakkeby/patches#30]
Hi, I have recently fixed some memory leaks and thought I might share. I have not checked whether they still exist in the current patches, but I am pretty sure they do. I linked to the commits in my build, so the fixes might not be exactly where they are in vanilla dwm, but it should be pretty straight forward, when looking at the patches. The fixes are all pretty simple.

[dwm-systray-6.2.diff](https://github.com/jzbor/MoonWM/commit/f39b15a3dce6f6f563e18fe97bcaf8e5da4634d5) (don't let the wrong commit message fool you)

[dwm-riodraw-6.2.diff/dwm-riodraw-nopidmatching-6.2.diff](https://github.com/jzbor/MoonWM/commit/2d598ad53c57eae058e99d715cb752b94519c9a1)

[dwm-pertag-6.2.diff](https://github.com/jzbor/MoonWM/commit/fa849104a0f17851fcc93cc9cfd7f3a4d81b94cd)

[dwm itself](https://github.com/jzbor/MoonWM/commit/a23aba96e0453413ae9be8e62d4ddefb09453171) (I will try to submit this upstream)

I also found a bug in focusonnetactive, that doesn't remove the borders on the previous client, if the newly focused client is on another monitor.
[dwm-focusonnetactive-6.2.diff](https://github.com/jzbor/MoonWM/commit/5f36b8b0133b566adf6b29f2923383fc35ed0610)

I have also found [this](https://github.com/jzbor/MoonWM/commit/defc4bbfdb1ad37196d018a198c3e44c8247db1d) memory leak in the xrdb patch but it is not part of the collection. Maybe it helps anyway. There is also another memory leak in the xrdb patch, that I was unable to fix.

I hope this is helpful, let me know, what you think of it.

**Comment by bakkeby** [comment]
Thanks, I'll have a look.

**Comment by jzbor** [comment]
Thanks once again for maintaing ;D

**Comment by bakkeby** [comment]
Looks good. The freeing of the scheme in dwm itself is something I already had in my builds, I believe I must have seen it in someone else's build at some point and just copied it. It makes sense for that to get submitted upstream.

Thanks!

**Comment by jzbor** [comment]
Ok thanks for the feedback!
