### ISSUE TITLE
the sha1 for dwm.c in dwm-cfacts-vanitygaps-6.2.diff is wrong(it doesn't exist in official dwm repo)

### ISSUE THREAD

**Issue by spitfire-hash** [bakkeby/patches#32]
When I tried to apply the patch `dwm-cfacts-vanitygaps-6.2.diff` with `git am -3` it said
```
error: sha1 information is lacking or useless (dwm.c).
error: could not build the fake ancestor
```
That is indeed true, the repo doesn't have any objects with the sha1 hashes(checked with `git show`):
```
index 5592c57..7d503cb 100644
```
Please update the patch with the correct hashes so that users can use 3-way merge for patching.

**Comment by bakkeby** [comment]
Yes it is indeed true that the base branch for these patches does not have the same commit ID as 6.2 and maybe I will go through and update them all at some point when I have more.

In this particular case I would not expect a three way merge would work either way as it is a patch on top of another patch (this is just patch 2 out of 2) so it would have the sha1 from [dwm-cfacts-6.2.diff](https://github.com/bakkeby/patches/blob/master/dwm/dwm-cfacts-6.2.diff) patch.

At some point in situations like this it will be easier to just apply patches manually. The tools can only help you so far (and you learn next to nothing from them).

**Comment by spitfire-hash** [comment]
Ah, I see. I didn't thought of this particular patch is formatted after a patch being applied, so sorry for that.

I have obviously applied the patch manually, I was just letting you know about this.

**Comment by bakkeby** [comment]
Closing this, most patches have been ported to 6.3 now.
