### ISSUE TITLE
[rioresize] Windows Don't Resize to the Proper Location

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [bakkeby/patches#34]
Hello,

I finally finished fully patching `dwm` and just want to say: thank you for riospawn and rioresize! They are perfect! I am having one issue though, I use dwmc to get all bindings using `sxhkd`. The issue I am facing is that for some reason `rioresize()` does not always resize the selected window to the desired location. This seems odd and I can't determine why this is happening.

I have the following [sxhkd](https://gitlab.com/FOSSilized_Daemon/dotfiles/-/blob/master/src/home/.config/sxhkd/sxhkdrc#L169) binding to resize the current window using `rioresize` and in my [config.def.h](https://gitlab.com/FOSSilized_Daemon/dwm/-/blob/master/src/config.def.h#L163) I do create a wrapper function for [dwm-signal (my dwmc)](https://gitlab.com/FOSSilized_Daemon/dwm/-/blob/master/src/dwm-signal#L43). I can't seem to resolve this issue and was wondering if it is an issue in upstream. I have not changed [rioresize](https://gitlab.com/FOSSilized_Daemon/dwm/-/blob/master/src/dwm.c#L1697).

**Comment by FOSSilizedDaemon** [comment]
Solution: needed an arrange(c->mon); see [commit](https://gitlab.com/FOSSilized_Daemon/dwm/-/commit/a36d14e4e77f874f89ca5e6d9d751ec1622f1cd2) for details.

**Comment by bakkeby** [comment]
The arrange, is that needed when riopositioning a tiled client on one monitor to become floating on another?

**Comment by FOSSilizedDaemon** [comment]
> The arrange, is that needed when riopositioning a tiled client on one monitor to become floating on another?

I guess so. Once I added it the issue went away on rebuild.
