### ISSUE TITLE
tabbed-bottomtabs patch for tabbed doesnt work 

### ISSUE THREAD

**Issue by siduck76** [bakkeby/patches#35]
Hi @bakkeby thanks for making the bottomtabs patch for tabbed , it doesnt seem to work for me . And the tabs arent clickable with mouse either and the tabs arent visible. Also they just show when I make the terminal fullscreen.

https://user-images.githubusercontent.com/59060246/126968346-71959d44-5d5d-4ac2-87f3-6db1e7504b5a.mp4

**Comment by bakkeby** [comment]
I can see the mouse click issue, but not sure how to reproduce your other issue about the tabs not showing.

**Comment by bakkeby** [comment]
I guess the autohide patch is interfering.

**Comment by siduck76** [comment]
maybe , My tabbed build : https://github.com/siduck76/tabbed/commit/d8dbd3ebc6aca5ff7eded63bfb8daf3957b37e6e

**Comment by siduck76** [comment]
unpatching autohide works.

**Comment by bakkeby** [comment]
https://tools.suckless.org/tabbed/patches/autohide/tabbed-autohide-20201222-dabf6a2.diff

Line 37, 38 we have this:

```c
+       for (i = 0; i < nclients; i++)
+           XMoveResizeWindow(dpy, clients[i]->win, 0, bh, ww, wh - bh);
```

this can be fixed with by setting the y position of `bh` to 0.

```c
+       for (i = 0; i < nclients; i++)
+           XMoveResizeWindow(dpy, clients[i]->win, 0, 0, ww, wh - bh);
```
