### ISSUE TITLE
netactiverules issue

### ISSUE THREAD

**Issue by luravoid** [bakkeby/patches#47]
Hi, I patched netactiverules manually and there wasn't any error during compilation but I can't get it to work.
I want this patch to stop focusing brave but no matter what focusonnetactive works the same

![image](https://user-images.githubusercontent.com/103893901/169117188-ce8a3e85-5ac0-43dd-8de4-4d45e73bc9d9.png)
![image](https://user-images.githubusercontent.com/103893901/169117299-1128a62c-8f96-4ed6-9275-2e7f196aba34.png)

I added this patch to dwm flexipatch build if it makes any difference

**Comment by bakkeby** [comment]
Can't think of any obvious reason why that would not work. If you have your build available somewhere then I can have a look, but I suspect that you have patched it just fine.

What is the particular behaviour you are observing? Is it automatically switching to the second tag when the brave browser starts or does it also keep going back to the brave browser on the second tag whenever you receive a message or another notification happens?

**Comment by luravoid** [comment]
I added build to my repo.
Yes, it is switching to the tag when i open new window and also when I open a link so the behavior is as if the patch wasn't there.
Maybe I didn't set correctly my config but I tried with different numbers and behaviour was still the same

**Comment by luravoid** [comment]
Also tried after finalizer and still the same 
![image](https://user-images.githubusercontent.com/103893901/169337344-5145de58-d403-4574-8a17-fcc66542cac4.png)

**Comment by luravoid** [comment]
I mean I patched manually second time after disabling focusonnetactive and using finalizer script and still this error showed up

**Comment by bakkeby** [comment]
Yes dwm-flexipatch has some changes so it does not have the plain tags array anymore. You can replace `LENGTH(tags)` with `NUMTAGS`.

**Comment by luravoid** [comment]
Thank you, it's working now
