### ISSUE TITLE
Resetlayout patch interfering with other layouts

### ISSUE THREAD

**Issue by paniash** [bakkeby/patches#5]
When I have one window open on any layout, it simply reverts back to tiling layout.

Could you please make changes, such that this patch works exclusively when in tiling layout mode only?

**Comment by bakkeby** [comment]
I assume that you are referring to this patch:
https://dwm.suckless.org/patches/resetlayout/

What you are asking doesn't make much sense as the intention of the patch is exactly that to reset the layout back to the tiling layout (or whatever layout 0 is in your build) when there is only one client left on the screen.

If you don't want this functionality then you simply would not take the patch in the first place.

**Comment by paniash** [comment]
Pardon me if I'm wrong but the description says that the mfact value is reset when one client is present.

**Comment by bakkeby** [comment]
It does that in addition to resetting the layout.

So, you'd want a patch that only resets mfact when there is one client?

**Comment by paniash** [comment]
I would very much appreciate if you could do that. Thanks!

**Comment by bakkeby** [comment]
The point of dwm is that you change the code to tailor it work exactly the way you want, which ultimately means _some_ exposure to the underlying code.

I don't actually have anything to do with the resetlayout patch, but of all the patches out there this will be one of the simplest ones.

https://dwm.suckless.org/patches/resetlayout/dwm-resetlayout-20200420-c82db69.diff

All that you need to do here is to delete the `setlayout(&default_layout);` line within the resetlayout function and you are good to go. As the `default_layout` variable is no longer used you'd just remove that one as well.

That would leave you with a function that only sets the mfact.

**Comment by paniash** [comment]
Ah, I see. Thanks a lot!
