### ISSUE TITLE
how to make windowrolerule patch working together with focusedontop patch?

### ISSUE THREAD

**Issue by adetabrani** [bakkeby/patches#62]
Recently I added a patch focusedontop and windowrollerule with the expectation that the Firefox popup window (e.g: bookmark manager) can switch focus with the main Firefox window, for more details you can see the following video.

The results were not as expected, popup firefox window still can't switch focus behind main firefox window

[simplescreenrecorder.webm](https://github.com/bakkeby/patches/assets/47938004/5943dc0c-46ca-4f53-8960-9076f16a17c5)

**Comment by bakkeby** [comment]
For me the firefox bookmark manager shows up with:
- the role of "Organizer"
- class of "firefox"
- instance of "Places"
- title of "Library"
- window type is normal

It also starts tiled for me as I don't have any rules for that.

Do you have a client rule for this window and do you also have alwaysontop = 1 for that?

**Comment by adetabrani** [comment]
![1689470219_Jul16_08:16:59](https://github.com/bakkeby/patches/assets/47938004/cbc8e4ec-4312-4f98-9d75-3220ce305ad5)

yes, you can check it in the following image

**Comment by bakkeby** [comment]
If you set alwaysontop = 0 then it should work as you expect as the window won't be moved on top of others.

**Comment by adetabrani** [comment]
> If you set alwaysontop = 0 then it should work as you expect as the window won't be moved on top of others.

still not working :(

**Comment by adetabrani** [comment]
noted, I've applied this patch and didn't get any errors while building, but maybe because too many patches I applied before made unexpected bugs appear, for now I will try to re-patch dan close the issue, maybe there is something I missed, thanks for the feedback

**Comment by adetabrani** [comment]
hi bakkeby, I've found an issue where the focusedontop patch doesn't work, the problem is in the function call to "arrange(selmon);" inside the function "focus(Client *c)", can be seen in the following [link](https://github.com/adetabrani/DWM-test/commit/e24df18537737007e188da132db676f9dcda53f4) 

1. previously I applied the noborder patch with modifications for unselected clients on this [link](https://www.reddit.com/r/suckless/comments/ix2olv/dwm_no_border_for_unselected_clients/) and I found the solution in the code you shared in the first comment section, but here I get a bug when I open a program that I have a rule for in my config.h file that assigns a specific tag to the program,in that section someone solved the problem by adding "arrange(selmon);" and problem is solved.
2. it looks like warp patch also can't work together with focusedontop patch, the warp function only works when opening a new window, the rest of the warp function doesn't work when switching focus. This bug can be solved if add "arrage(selmon);"

The conclusion is focusedontop patch works if the "arrange(selmon);" are removed, but on the other hand if I remove it then I will experience bugs in points 1 and 2. Is it possible to make the patches work with each other?

You can do a test on the repository that I have prepared at this [link](https://github.com/adetabrani/DWM-test)

**Comment by bakkeby** [comment]
Yes it is not great. The focusedontop patch will need a complete rewrite to address these issues.

**Comment by bakkeby** [comment]
I added https://github.com/bakkeby/patches/blob/master/dwm/dwm-focusedontop-6.4.diff which should work better in all aspects. I don't include the window type rule change, but that can be added separately if need be.

**Comment by adetabrani** [comment]
working perfectly, thanks for the help

**Comment by adetabrani** [comment]
[simplescreenrecorder.webm](https://github.com/bakkeby/patches/assets/47938004/68efd178-dacf-402b-8f86-6d192d274e8b)

Hi Bakkeby, recently i used dunst, here i noticed that dunst window is overlapping with another window, for that i tried to update the last focusedontop patch by adding wintype functionality, i think it works but when i try to focus the window which is below the window zoom position, there is still overlap.

is there still a shortage in adding code for the wintype function? you can check it on my repo [here](https://github.com/adetabrani/dwm)

**Comment by bakkeby** [comment]
The dunst notification window is not managed by the window manager so there is not much you can do about that I recon.

**Comment by adetabrani** [comment]
😭 whereas I would like the dust window to stay on top of other windows when I focus on any window. 
Thanks for the feedback

**Comment by adetabrani** [comment]
this behavior can be got when i use patch focusedontop 6.3 but i will re-experience bugs related to warp and noborder if i apply it

**Comment by adetabrani** [comment]
closed for this issue, I've used cursorwarp patch instead of warp patch for feature compatibility reasons
