### ISSUE TITLE
[BUG] st-background-image

### ISSUE THREAD

**Issue by sudzxd** [bakkeby/patches#63]
While installing the patch background-image for st, if the image is specified in .ff format st fails to load. I tried it with the older patch also but it does not seem to work.

**Comment by bakkeby** [comment]
That patch does not have anything to do with this repository, but do you have other patches applied?

Looking at https://github.com/bakkeby/st-flexipatch/blob/master/patch/background_image_x.c I see that the patch would conflict with the alpha patch.

**Comment by sudzxd** [comment]
Thanks for the help! I do have alpha installed. Will try removing the alpha patch and installing it again.

**Comment by bakkeby** [comment]
Or just add the adjustments that is made to the background-image patch to make it work with the alpha patch. Example in the file I referred to.

**Comment by sudzxd** [comment]
Thanks! But since i will be loading an image in st then the alpha patch is not needed. Thanks for the advice!
