### ISSUE TITLE
Auto hide renamed-scrachpachs when a new window is spawned

### ISSUE THREAD

**Issue by mahor1221** [bakkeby/patches#67]
Would it be possible to auto hide scratchpads when, for example, a new window is spawned? 
It's a combination of `LOSEFULLSCREEN_PATCH` and `RENAMED_SCRATCHPADS_AUTO_HIDE_PATCH`. I attempted to implement it by adding a new branch to the `unfocus` functions, but it didn't work.

```c 
        // line 4370, unfocus(...) function:
        . . .
        
        // I've added this part
	#if RENAMED_SCRATCHPADS_PATCH && RENAMED_SCRATCHPADS_AUTO_HIDE_PATCH && LOSEFULLSCREEN_PATCH
        if (c->scratchkey != 0 && !(c->tags & c->mon->tagset[c->mon->seltags])))
                c->tags = 0;
        else
			
	#elif LOSEFULLSCREEN_PATCH
	if (c->isfullscreen && ISVISIBLE(c) && c->mon == selmon && nextfocus && !nextfocus->isfloating)

        . . .

```

**Comment by mahor1221** [comment]
I've just found https://github.com/bakkeby/dwm-commented. Awesome! I'll try implementing the feature I personally want my self but still, any help would be appreciated :)

**Comment by bakkeby** [comment]
I have a working solution for auto-hiding a fullscreen scratchpad when a new client is spawned - that way the next time you toggle the scratchpad it will (still) be in fullscreen.

Based on your wording though it _sounds_ like you want the scratchpad to go away whenever it loses focus. Possible to do for sure, but it would also be super annoying I recon unless you were to  isolate the behaviour to a specific client. For example it would be impossible to view two different scratchpads side-by-side. That said if this is something that may add value in a workflow then I'd add that as a different toggle.

**Comment by mahor1221** [comment]
Ah, I apologize for my incorrect wording. The following behavior you've described is exactly what I'm looking for:

> I have a working solution for auto-hiding a fullscreen scratchpad when a new client is spawned - that way the next time you toggle the scratchpad it will (still) be in fullscreen.

**Comment by bakkeby** [comment]
```diff
diff --git a/dwm.c b/dwm.c
index 66a380b..7497c65 100644
--- a/dwm.c
+++ b/dwm.c
@@ -2704,11 +2704,11 @@ motionnotify(XEvent *e)
        #if !FOCUSONCLICK_PATCH
        static Monitor *mon = NULL;
        Monitor *m;
-       #endif // FOCUSONCLICK_PATCH
-       Bar *bar;
        #if LOSEFULLSCREEN_PATCH
        Client *sel;
        #endif // LOSEFULLSCREEN_PATCH
+       #endif // FOCUSONCLICK_PATCH
+       Bar *bar;
        XMotionEvent *ev = &e->xmotion;

        if ((bar = wintobar(ev->window))) {
@@ -4373,13 +4373,24 @@ unfocus(Client *c, int setfocus, Client *nextfocus)
        selmon->pertag->prevclient[selmon->pertag->curtag] = c;
        #endif // SWAPFOCUS_PATCH
        #if LOSEFULLSCREEN_PATCH
-       if (c->isfullscreen && ISVISIBLE(c) && c->mon == selmon && nextfocus && !nextfocus->isfloating)
+       if (c->isfullscreen && ISVISIBLE(c) && c->mon == selmon && nextfocus && !nextfocus->isfloating) {
+               #if RENAMED_SCRATCHPADS_PATCH && RENAMED_SCRATCHPADS_AUTO_HIDE_PATCH
+               #if FAKEFULLSCREEN_CLIENT_PATCH
+               if (c->scratchkey != 0 && c->fakefullscreen != 1)
+                       togglescratch(&((Arg) {.v = (const char*[]){ &c->scratchkey, NULL } }));
+               #else
+               if (c->scratchkey != 0)
+                       togglescratch(&((Arg) {.v = (const char*[]){ &c->scratchkey, NULL } }));
+               #endif // FAKEFULLSCREEN_CLIENT_PATCH
+               else
+               #endif // RENAMED_SCRATCHPADS_AUTO_HIDE_PATCH
                #if FAKEFULLSCREEN_CLIENT_PATCH
                if (c->fakefullscreen != 1)
                        setfullscreen(c, 0);
                #else
                setfullscreen(c, 0);
                #endif // #if FAKEFULLSCREEN_CLIENT_PATCH
+       }
        #endif // LOSEFULLSCREEN_PATCH
        grabbuttons(c, 0);
        #if !BAR_FLEXWINTITLE_PATCH
```

The above is a change that I just now pushed for dwm-flexipatch.

The basic idea is that if the conditions are right, i.e
   - the window is fullscreen and
   - it is not in fake fullscreen and
   - it is visible and
   - it is a scratchpad client

then we just make a call to `togglescratch` to hide it. What is complicated here is passing the `scratchkey` as an argument to the function.

**Comment by mahor1221** [comment]
Thank you so much! You have saved me days of work, and now my desktop is finally perfect.

**Comment by mahor1221** [comment]
I've also added a `c->isfloating` condition for my personal use case, as some of my scratchpads are not fullscreen but they cover 100% of the screen except the bar.

```diff
-       if (c->isfullscreen && ISVISIBLE(c) && c->mon == selmon && nextfocus && !nextfocus->isfloating)
+       if (c->isfloating || c->isfullscreen && ISVISIBLE(c) && c->mon == selmon && nextfocus && !nextfocus->isfloating) {
```
