### ISSUE TITLE
wintitleactions + zoomswap

### ISSUE THREAD

**Issue by vide0hanz** [bakkeby/patches#8]
FYI, the changes made to the `prevtiled()` function in the winttileactions patch appear to slightly break the behavior of zoomswap, probably due to this statement being absent in wintitleactions:

    +	if (!c || c == c->mon->clients)
    +		return NULL;

Without this, zoomswap seems to get confused when you move a client to a new tag. Calling `zoom` just places the newly moved client back on the last tag. I'm not sure how consistent this bug is, I only briefly tested it, but adding the above statement back in appears to solve it.

**Comment by bakkeby** [comment]
I see. I'll correct the zoomswap patch or simply remove it. 

Better refer to:
https://dwm.suckless.org/patches/zoomswap/dwm-zoomswap-6.2.diff

I originally thought that findbefore was actually just doing the opposite of nexttiled, but the function in the original patch actually does something different than what the prevtiled function as part of wintitleactions does. Hence the name clash.

**Comment by vide0hanz** [comment]
Gotcha. Admittedly I'm not sure exactly why adding that bit back in resolved it, but perhaps it's better to keep the vanilla zoomswap patch as is to ensure no conflicts arise at all.

**Comment by bakkeby** [comment]
Yes better go with the vanilla one, otherwise you could end up with odd behaviour when it comes to hiding clients.

**Comment by bakkeby** [comment]
Now removed. Thanks.
