### ISSUE TITLE
window activity freeze when open more than one window in dwm through dbus

### ISSUE THREAD

**Issue by nirodhvana** [bakkeby/patches#87]
The window activity freezes when i open more than one window in dwm that is launched through dbus.

this only happens with my patched version of dwm and only when launched usinh dbus

Here are my patches 
https://github.com/nirodhvana/sucklesser/tree/master/dwm/patches

**Comment by bakkeby** [comment]
Do you have a notification manager running? If not then try running dunst.

I have seen programs lock up waiting for their notification to be picked up to be presented to the user.

**Comment by nirodhvana** [comment]
So, i replaced xcompmgr with compton in xinitrc and now it seems to work fine. This may have been cause by a bug in xcompmgr

**Comment by bakkeby** [comment]
I believe that xcompmgr do have issues with native border changes. In general it is not a good idea to use these kind of noborder patches as they can have obscure side effects.

**Comment by nirodhvana** [comment]
> I believe that xcompmgr do have issues with native border changes. In general it is not a good idea to use these kind of noborder patches as they can have obscure side effects.

It works fine now so ill just close the issue

**Comment by nirodhvana** [comment]
> I believe that xcompmgr do have issues with native border changes. In general it is not a good idea to use these kind of noborder patches as they can have obscure side effects.

It works fine now so ill just close this issue
